# Generated by Django 2.2.5 on 2019-09-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_cost', models.FloatField(max_length=20)),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Restaurants')),
            ],
        ),
    ]
